from discord import Permissions

def role_permissions(permissions_dict: dict):
    return Permissions(
        create_instant_invite=permissions_dict.get('create_instant_invite', False),
        kick_members=permissions_dict.get('kick_members', False),
        ban_members=permissions_dict.get('ban_members', False),
        administrator=permissions_dict.get('administrator', False),
        manage_channels=permissions_dict.get('manage_channels', False),
        manage_guild=permissions_dict.get('manage_guild', False),
        add_reactions=permissions_dict.get('add_reactions', False),
        view_audit_log=permissions_dict.get('view_audit_log', False),
        priority_speaker=permissions_dict.get('priority_speaker', False),
        stream=permissions_dict.get('stream', False),
        read_messages=permissions_dict.get('read_messages', False),
        send_messages=permissions_dict.get('send_messages', False),
        send_tts_messages=permissions_dict.get('send_tts_messages', False),
        manage_messages=permissions_dict.get('manage_messages', False),
        embed_links=permissions_dict.get('embed_links', False),
        attach_files=permissions_dict.get('attach_files', False),
        read_message_history=permissions_dict.get('read_message_history', False),
        mention_everyone=permissions_dict.get('mention_everyone', False),
        external_emojis=permissions_dict.get('external_emojis', False),
        view_guild_insights=permissions_dict.get('view_guild_insights', False),
        connect=permissions_dict.get('connect', False),
        speak=permissions_dict.get('speak', False),
        mute_members=permissions_dict.get('mute_members', False),
        deafen_members=permissions_dict.get('deafen_members', False),
        move_members=permissions_dict.get('move_members', False),
        use_voice_activation=permissions_dict.get('use_voice_activation', False),
        change_nickname=permissions_dict.get('change_nickname', False),
        manage_nicknames=permissions_dict.get('manage_nicknames', False),
        manage_roles=permissions_dict.get('manage_roles', False),
        manage_webhooks=permissions_dict.get('manage_webhooks', False),
        manage_expressions=permissions_dict.get('manage_expressions', False),
        use_application_commands=permissions_dict.get('use_application_commands', False),
        request_to_speak=permissions_dict.get('request_to_speak', False),
        manage_events=permissions_dict.get('manage_events', False),
        manage_threads=permissions_dict.get('manage_threads', False),
        create_public_threads=permissions_dict.get('create_public_threads', False),
        create_private_threads=permissions_dict.get('create_private_threads', False),
        external_stickers=permissions_dict.get('external_stickers', False),
        send_messages_in_threads=permissions_dict.get('send_messages_in_threads', False),
        use_embedded_activities=permissions_dict.get('use_embedded_activities', False),
        moderate_members=permissions_dict.get('moderate_members', False),
        view_creator_monetization_analytics=permissions_dict.get('view_creator_monetization_analytics', False),
        use_soundboard=permissions_dict.get('use_soundboard', False),
        create_expressions=permissions_dict.get('create_expressions', False),
        create_events=permissions_dict.get('create_events', False),
        use_external_sounds=permissions_dict.get('use_external_sounds', False),
        send_voice_messages=permissions_dict.get('send_voice_messages', False),
        send_polls=permissions_dict.get('send_polls', False),
        use_external_apps=permissions_dict.get('use_external_apps', False),
    )

# permissions_list = [
#     ('create_instant_invite', False),
#     ('kick_members', False),
#     ('ban_members', False),
#     ('administrator', False),
#     ('manage_channels', False),
#     ('manage_guild', False),
#     ('add_reactions', False),
#     ('view_audit_log', False),
#     ('priority_speaker', False),
#     ('stream', False),
#     ('read_messages', False),
#     ('send_messages', True),
#     ('send_tts_messages', False),
#     ('manage_messages', False),
#     ('embed_links', True),
#     ('attach_files', False),
#     ('read_message_history', True),
#     ('mention_everyone', False),
#     ('external_emojis', False),
#     ('view_guild_insights', False),
#     ('connect', False),
#     ('speak', False),
#     ('mute_members', False),
#     ('deafen_members', False),
#     ('move_members', False),
#     ('use_voice_activation', False),
#     ('change_nickname', False),
#     ('manage_nicknames', False),
#     ('manage_roles', False),
#     ('manage_webhooks', False),
#     ('manage_expressions', False),
#     ('use_application_commands', False),
#     ('request_to_speak', False),
#     ('manage_events', False),
#     ('manage_threads', False),
#     ('create_public_threads', False),
#     ('create_private_threads', False),
#     ('external_stickers', False),
#     ('send_messages_in_threads', False),
#     ('use_embedded_activities', False),
#     ('moderate_members', False),
#     ('view_creator_monetization_analytics', False),
#     ('use_soundboard', False),
#     ('create_expressions', False),
#     ('create_events', False),
#     ('use_external_sounds', False),
#     ('send_voice_messages', False),
#     ('send_polls', False),
#     ('use_external_apps', False),
# ]

# # Call the function to create a Permissions object
# permissions = create_permissions(permissions_list)